package:
  name: coffea
  version: local

source:
  git_rev: master
  git_url: https://github.com/CoffeaTeam/coffea.git

requirements:
  build:
    - python
    - setuptools
    - six
    - flake8
    - pytest-runner 
    - awkward
    - uproot
    - pandas
    - ipywidgets
    - scipy
    - cloudpickle
    - lz4
    - packaging
    - matplotlib
    - mplhep
    - tqdm
    - lz4
    - numba
    - pep517
    - cmake
    - ipython

  host:
    - python

  run:
    - python
    - six
    - awkward
    - uproot
    - pandas
    - ipywidgets
    - scipy
    - cloudpickle
    - lz4
    - packaging
    - matplotlib
    - mplhep
    - tqdm
    - lz4
    - numba
    - ipython

tests:
  imports:
    - coffea

about:
  home: